apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: sqlserver-pvc-dev
  namespace: gestionalarme-dev

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: default