apiVersion: v1
kind: Secret

metadata:
  name: gestionalarme-secret
  namespace: gestionalarme-prod

type: Opaque

stringData:
  SA_PASSWORD: "@dmin123"

  ConnectionStrings__SqlServerConnection: "Server=sqlserver-service;Database=PFEGestionAlert;User Id=sa;Password=@dmin123;TrustServerCertificate=True"