// <auto-generated />
using System;
using CollectManagement.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220091658_AddSMSToProject")]
    partial class AddSMSToProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectManagement.Domain.Alertes.Alerte", b =>
                {
                    b.Property<Guid>("AlerteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DispositifId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Traiter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlerteId");

                    b.HasIndex("DispositifId");

                    b.HasIndex("TypeId");

                    b.ToTable("Alerte");
                });

            modelBuilder.Entity("CollectManagement.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreCapteur")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("CollectManagement.Domain.Employess.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rfid")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("CollectManagement.Domain.JoursFeries.JourFerie", b =>
                {
                    b.Property<Guid>("JourFerieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JourFerieId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("JourFerie");
                });

            modelBuilder.Entity("CollectManagement.Domain.Maintenances.Maintenance", b =>
                {
                    b.Property<Guid>("MaintenanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("T1Alerte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T2Assignment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T3Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T4Completion")
                        .HasColumnType("datetime2");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("CollectManagement.Domain.Maintenances.MaintenanceCaptureHistory", b =>
                {
                    b.Property<Guid>("MaintenanceCaptureHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaintenanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaintenanceCaptureHistoryId");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MaintenanceId");

                    b.ToTable("MaintenanceCaptureHistory");
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.Planning", b =>
                {
                    b.Property<Guid>("PlanningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanningId");

                    b.ToTable("Planning");
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.PlanningDevice", b =>
                {
                    b.Property<Guid>("PlanningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanningId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("PlanningDevice", (string)null);
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.PlanningEmployee", b =>
                {
                    b.Property<Guid>("PlanningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanningId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PlanningEmployee", (string)null);
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.PlanningShift", b =>
                {
                    b.Property<Guid>("PlanningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanningId", "ShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("PlanningShift", (string)null);
                });

            modelBuilder.Entity("CollectManagement.Domain.SMS.SMS", b =>
                {
                    b.Property<Guid>("SMSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPrenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SMSId");

                    b.ToTable("SMS");
                });

            modelBuilder.Entity("CollectManagement.Domain.SMS.SMSDevice", b =>
                {
                    b.Property<Guid>("SMSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SMSId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("SMSDevice", (string)null);
                });

            modelBuilder.Entity("CollectManagement.Domain.Shifts.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("CollectManagement.Domain.Societes.Societe", b =>
                {
                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Capital")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CodeSociete")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOverture")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Fax1")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Fax2")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatriculeFiscal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rne")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone1")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Telephone2")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("SocieteId");

                    b.ToTable("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Types.Type", b =>
                {
                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DureeNominal")
                        .HasColumnType("int");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", b =>
                {
                    b.Property<Guid>("RoleUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleRoleUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleUtilisateurId");

                    b.ToTable("RoleUtilisateur");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RoleUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.HasIndex("RoleUtilisateurId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("CollectManagement.Domain.Alertes.Alerte", b =>
                {
                    b.HasOne("CollectManagement.Domain.Devices.Device", "Dispositif")
                        .WithMany()
                        .HasForeignKey("DispositifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Types.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispositif");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CollectManagement.Domain.Maintenances.Maintenance", b =>
                {
                    b.HasOne("CollectManagement.Domain.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Employess.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CollectManagement.Domain.Maintenances.MaintenanceCaptureHistory", b =>
                {
                    b.HasOne("CollectManagement.Domain.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Employess.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Maintenances.Maintenance", "Maintenance")
                        .WithMany()
                        .HasForeignKey("MaintenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Employee");

                    b.Navigation("Maintenance");
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.PlanningDevice", b =>
                {
                    b.HasOne("CollectManagement.Domain.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Plannings.Planning", "Planning")
                        .WithMany("PlanningDevices")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.PlanningEmployee", b =>
                {
                    b.HasOne("CollectManagement.Domain.Employess.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Plannings.Planning", "Planning")
                        .WithMany("PlanningEmployees")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.PlanningShift", b =>
                {
                    b.HasOne("CollectManagement.Domain.Plannings.Planning", "Planning")
                        .WithMany("PlanningShifts")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Shifts.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planning");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("CollectManagement.Domain.SMS.SMSDevice", b =>
                {
                    b.HasOne("CollectManagement.Domain.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.SMS.SMS", "SMS")
                        .WithMany("SMSDevices")
                        .HasForeignKey("SMSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("SMS");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", b =>
                {
                    b.OwnsMany("CollectManagement.Domain.Utilisateurs.Entities.Navigation", "Navigations", b1 =>
                        {
                            b1.Property<string>("NavigationId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid>("RoleUtilisateurId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Actions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NavigationId", "RoleUtilisateurId");

                            b1.HasIndex("RoleUtilisateurId");

                            b1.ToTable("Navigation");

                            b1.WithOwner()
                                .HasForeignKey("RoleUtilisateurId");

                            b1.OwnsMany("CollectManagement.Domain.Utilisateurs.Entities.NavigationSection", "Sections", b2 =>
                                {
                                    b2.Property<string>("SectionId")
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Actions")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NavigationId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<Guid>("NavigationRoleUtilisateurId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("SectionId");

                                    b2.HasIndex("NavigationId", "NavigationRoleUtilisateurId");

                                    b2.ToTable("NavigationSection");

                                    b2.WithOwner()
                                        .HasForeignKey("NavigationId", "NavigationRoleUtilisateurId");
                                });

                            b1.Navigation("Sections");
                        });

                    b.Navigation("Navigations");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.HasOne("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", "RoleUtilisateur")
                        .WithMany()
                        .HasForeignKey("RoleUtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RoleUtilisateur");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Plannings.Planning", b =>
                {
                    b.Navigation("PlanningDevices");

                    b.Navigation("PlanningEmployees");

                    b.Navigation("PlanningShifts");
                });

            modelBuilder.Entity("CollectManagement.Domain.SMS.SMS", b =>
                {
                    b.Navigation("SMSDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
